Repository krishnapatidar458/hacktoberfest2023, pull requests merged in 2023-10, with the labels that each got.

#15 otp_generator
  java/OTPGenerator.java
Labels: hacktoberfest, hacktoberfest2023, hacktoberfest-accepted

#14 added huffmann code
  python/Huffman_Algorithm.py
Labels: hacktoberfest-accepted

#21 Update CONTRIBUTING.md
  CONTRIBUTING.md
Labels: hacktoberfest-accepted

#24 Update README.md
  Online Shopping Project/README.md
Labels: hacktoberfest2023, hacktoberfest-accepted

#25 Revert "Update README.md"
  Image Processing and Generation/README.md
Labels: hacktoberfest, hacktoberfest2023, hacktoberfest-accepted

#16 Calculator Program Added in file Calculator.c
  c/Calculator.c
Labels: hacktoberfest-accepted

#31 Create toposort using bfs.cpp
  cpp/toposort using bfs.cpp
Labels: hacktoberfest-accepted

#30 Add files via upload
  toposort_by_bfs.cpp
Labels: hacktoberfest-accepted

#32 Update pattern.py
  python/pattern.py
Labels: hacktoberfest-accepted
